"""Add Audio Tag

Revision ID: 194383a62263
Revises: 3647384eb0d6
Create Date: 2021-04-19 21:32:44.793211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194383a62263'
down_revision = '3647384eb0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_tags')
    # ### end Alembic commands ###
